### Function

In [2]:
x = 1
y = 2
z = x + y*9

print(x, y, z)

1 2 19


In [3]:
def add_numbers(x,y):
    return x + y

add_numbers(2.5,3)

5.5

In [4]:
def add_numbers(x,y,z = None):
    if(z == None):
        return x+y
    else: 
        return x+y+z
    
print(add_numbers(12,3))
print(add_numbers(12,3,4))

15
19


In [9]:
def add_numbers(x, y, z=None, flag=False):
    if (flag):
        print('Flag is true!')
    if (z==None):
        return x + y
    else:
        return x + y + z
    
a = add_numbers
print(a(1, 2, False))
print(a(1, 2, None, True))
print(a(1, 2, 3, True))

3
Flag is true!
3
Flag is true!
6


### Scaler Objects

In [10]:
x = [1,2,'a']
type(x)

list

In [11]:
x.append('obj')
print(x)

[1, 2, 'a', 'obj']


In [15]:
#concatenate lists
[1,2] + [3,4]

[1, 2, 3, 4]

In [16]:
#repeat lists
[1, 2, 3] * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

### Looping

In [13]:
for item in x:
    print(item)

1
2
a
obj


In [14]:
i=0
while( i != len(x) ):
    print(x[i])
    i = i + 1

1
2
a
obj


### split

In [17]:
name = 'Christopher Arthur Hansen Brooks'
firstname = name.split(' ')[0] # [0] selects the first element of the list
lastname = 'Christopher Arthur Hansen Brooks'.split(' ')[-1] # [-1] selects the last element of the list
print(firstname)
print(lastname)

Christopher
Brooks


### dictionary: keys & values

In [19]:
x = {'hq':'ha@','yg':'yg@'}
x['yg']

'yg@'

In [21]:
x['Kevyn Collins-Thompson'] = 'KC@'
x['Kevyn Collins-Thompson']
print(x)

{'hq': 'ha@', 'yg': 'yg@', 'Kevyn Collins-Thompson': 'KC@'}


In [22]:
for name in x:
    print(name)

hq
yg
Kevyn Collins-Thompson


In [23]:
for i in x.values():
    print(i)

ha@
yg@
KC@


### unpack a sequence into different variables

In [2]:
x = ('Christopher', 'Brooks', 'brooksch@umich.edu', 'Ann Arbor')
fname, lname, email,location = x
print(location)

Ann Arbor


### work on mpg.csv file

In [1]:
import csv

%precision 2 

with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))

In [10]:
type(mpg)

list

In [11]:
mpg[:2]

[OrderedDict([('', '1'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'auto(l5)'),
              ('drv', 'f'),
              ('cty', '18'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '2'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'manual(m5)'),
              ('drv', 'f'),
              ('cty', '21'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')])]

In [12]:
mpg[0].keys()

odict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

#### find the average cty fuel economy across all cars. All values in the dictionaries are strings, so we need to convert to float

In [13]:
sum(float(d['cty']) for d in mpg)/len(mpg)

16.86

#### Use set to return the unique values for the number of cylinders the cars in our dataset have.

In [14]:
cylinders = set(d['cyl'] for d in mpg)
cylinders

{'4', '5', '6', '8'}

#### we are grouping the cars by number of cylinder, and finding the average cty mpg for each group

In [15]:
CtyMpgByCyl = []

for c in cylinders: # iterate over all the cylinder levels
    summpg = 0
    cyltypecount = 0
    for d in mpg: # iterate over all dictionaries
        if d['cyl'] == c: # if the cylinder level type matches,
            summpg += float(d['cty']) # add the cty mpg
            cyltypecount += 1 # increment the count
    CtyMpgByCyl.append((c, summpg / cyltypecount)) # append the tuple ('cylinder', 'avg mpg')

CtyMpgByCyl.sort(key=lambda x1: x1[0])
CtyMpgByCyl

[('4', 21.01), ('5', 20.50), ('6', 16.22), ('8', 12.57)]

In [16]:
vehicleclass = set(d['class'] for d in mpg) # what are the class types
vehicleclass

{'2seater', 'compact', 'midsize', 'minivan', 'pickup', 'subcompact', 'suv'}

In [17]:
HwyMpgByClass = []

for t in vehicleclass: # iterate over all the vehicle classes
    summpg = 0
    vclasscount = 0
    for d in mpg: # iterate over all dictionaries
        if d['class'] == t: # if the cylinder amount type matches,
            summpg += float(d['hwy']) # add the hwy mpg
            vclasscount += 1 # increment the count
    HwyMpgByClass.append((t, summpg / vclasscount)) # append the tuple ('class', 'avg mpg')

HwyMpgByClass.sort(key=lambda x: x[1])
HwyMpgByClass

[('pickup', 16.88),
 ('suv', 18.13),
 ('minivan', 22.36),
 ('2seater', 24.80),
 ('midsize', 27.29),
 ('subcompact', 28.14),
 ('compact', 28.30)]

### Python: Date, Time

In [18]:
import datetime as dt
import time as tm

### Python: Objects and map()

#### class

In [20]:
#class
class Person:
    department = 'School of Information' #a class variable

    def set_name(self, new_name): #a method
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location

In [21]:
person = Person()
person.set_name('Christopher Brooks')
person.set_location('Ann Arbor, MI, USA')
print('{} live in {} and works in the department {}'.format(person.name, person.location, person.department))

Christopher Brooks live in Ann Arbor, MI, USA and works in the department School of Information


#### map( )

In [22]:
#map()
store1 = [10.00, 11.00, 12.34, 2.34]
store2 = [9.00, 11.10, 12.34, 2.01]
cheapest = map(min, store1, store2)
cheapest

In [23]:
for item in cheapest:
    print(item)

9.0
11.0
12.34
2.01


### Python: Lambda and List Comprehensions

#### lambda

In [26]:
my_function = lambda a, b, c : a + b

print(my_function(1, 5, 3))

6


#### for loop vs. list

In [28]:
my_list = []
for number in range(0, 1000):
    if number % 2 == 0:
        my_list.append(number)
my_list

print(len(my_list))

500


In [29]:
#list:
my_list = [number for number in range(0,1000) if number % 2 == 0]

print(len(my_list))

500


### Python: Numpy

In [31]:
import numpy as np

mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

In [32]:
#multi-dimensional array
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [33]:
n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
print(n)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


In [34]:
n = n.reshape(3, 5) # reshape array to be 3x5
print(n)

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]]


### Iterating Over Arrays

In [35]:
test = np.random.randint(0,10,(4,3))
print(test)

[[9 1 6]
 [4 1 6]
 [5 3 5]
 [6 1 8]]


In [36]:
#iterate by row:
#The enumerate() function adds a counter to an iterable
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [9 1 6]
row 1 is [4 1 6]
row 2 is [5 3 5]
row 3 is [6 1 8]


In [37]:
test2 = test**2
test2

array([[81,  1, 36],
       [16,  1, 36],
       [25,  9, 25],
       [36,  1, 64]])

In [38]:
#Use zip to iterate over multiple iterables
for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)

[9 1 6] + [81  1 36] = [90  2 42]
[4 1 6] + [16  1 36] = [20  2 42]
[5 3 5] + [25  9 25] = [30 12 30]
[6 1 8] + [36  1 64] = [42  2 72]
